// lang.js —— TraceLife 多语言支持：中英文词典、语言管理与日期本地化。
'use strict';

const LANG_KEY = 'hobby-diary:lang';
const LANG_DICT = {
  '连续': ['Streak', 'en'],
  '天': ['days', 'en'],
  '累计': ['Total', 'en'],
  '条记录': ['records', 'en'],
  '今日': ['Today', 'en'],
  '日历': ['Calendar', 'en'],
  '统计': ['Stats', 'en'],
  '项目': ['Projects', 'en'],
  '设置': ['Settings', 'en'],
  '爱好': ['Hobbies', 'en'],
  '工作': ['Work', 'en'],
  '健康': ['Health', 'en'],
  '很差': ['Terrible', 'en'],
  '不佳': ['Bad', 'en'],
  '一般': ['Okay', 'en'],
  '不错': ['Good', 'en'],
  '超棒': ['Amazing', 'en'],
  '体重': ['Weight', 'en'],
  '血糖': ['Blood Sugar', 'en'],
  '血压': ['Blood Pressure', 'en'],
  '早': ['Morning', 'en'],
  '中': ['Noon', 'en'],
  '晚': ['Evening', 'en'],
  '空腹': ['Fasting', 'en'],
  '餐后2小时': ['2h After Meal', 'en'],
  '睡前': ['Bedtime', 'en'],
  '完成': ['Done', 'en'],
  '进行中': ['In Progress', 'en'],
  '未完成': ['Not Done', 'en'],
  '宁静': ['Calm', 'en'],
  '钢琴': ['Piano', 'en'],
  '轻快': ['Bright', 'en'],
  '活力': ['Energetic', 'en'],
  '电子': ['Electronic', 'en'],
  '海岛': ['Island', 'en'],
  '添加记录': ['Add Record', 'en'],
  '管理项目': ['Manage Projects', 'en'],
  '回到今天': ['Back to Today', 'en'],
  '选择日期': ['Select Date', 'en'],
  '项': ['items', 'en'],
  '心情': ['Mood', 'en'],
  '专注计时': ['Focus Timer', 'en'],
  '今天已专注': ['Focused Today', 'en'],
  '开始专注': ['Start Focus', 'en'],
  '结束': ['Finish', 'en'],
  '暂停': ['Pause', 'en'],
  '继续': ['Resume', 'en'],
  '自由计时：结束时可一键把本次时长保存到今天的记录（时长不是必填，不想要直接放弃即可）。': ['Free timing: save the duration to today\'s record when done (optional, can discard).', 'en'],
  '先添加项目，再开始专注计时': ['Add a project first to start focusing', 'en'],
  '这一天还没有记录': ['No records on this day', 'en'],
  '去记录': ['Record', 'en'],
  '回到本月': ['Back to This Month', 'en'],
  '上个月': ['Previous Month', 'en'],
  '下个月': ['Next Month', 'en'],
  '打卡': ['days', 'en'],
  '本月记录天数': ['Days This Month', 'en'],
  '累计记录': ['Total Records', 'en'],
  '当前连续': ['Current Streak', 'en'],
  '最长连续': ['Longest Streak', 'en'],
  '今日专注（分钟）': ['Focus Today (min)', 'en'],
  '近7天专注（分钟）': ['Focus 7D (min)', 'en'],
  '最近 14 天': ['Last 14 Days', 'en'],
  '项目排行': ['Project Ranking', 'en'],
  '全部': ['All', 'en'],
  '近30天': ['30-Day', 'en'],
  '趋势': ['Trend', 'en'],
  '数据点太少（至少 2 条），继续记录吧': ['Not enough data points (need at least 2). Keep recording!', 'en'],
  '我的项目': ['My Projects', 'en'],
  '添加新项目': ['Add New Project', 'en'],
  '分类': ['Category', 'en'],
  '图标': ['Icon', 'en'],
  '名称': ['Name', 'en'],
  '颜色': ['Color', 'en'],
  '保存': ['Save', 'en'],
  '取消': ['Cancel', 'en'],
  '编辑项目': ['Edit Project', 'en'],
  '添加新爱好': ['Add New Project', 'en'],
  '编辑爱好': ['Edit Project', 'en'],
  '请先到「项目」页添加项目。': ['Please add a project on the Projects page first.', 'en'],
  '请先添加项目': ['Please add a project first', 'en'],
  '请先选择项目': ['Please choose a project first', 'en'],
  '已添加项目 🎨': ['Project added 🎨', 'en'],
  '删除所有项目和记录，且无法恢复。请先导出备份。': ['Deletes all projects and records. This cannot be undone. Please export a backup first.', 'en'],
  '清空全部数据': ['Clear All Data', 'en'],
  '数据备份': ['Data Backup', 'en'],
  '更新说明': ['Changelog', 'en'],
  '存储空间': ['Storage', 'en'],
  '应用锁': ['App Lock', 'en'],
  '背景音乐': ['Background Music', 'en'],
  '外观': ['Appearance', 'en'],
  '语言': ['Language', 'en'],
  '查看更新说明': ['View Changelog', 'en'],
  '导出 JSON': ['Export JSON', 'en'],
  '导入 JSON': ['Import JSON', 'en'],
  '浅色': ['Light', 'en'],
  '深色': ['Dark', 'en'],
  '已用': ['Used', 'en'],
  '剩余': ['Left', 'en'],
  '共': ['Total', 'en'],
  '计算中…': ['Calculating…', 'en'],
  '当前浏览器不支持查看存储空间': ['Storage info not supported in this browser', 'en'],
  '暂时无法获取存储空间': ['Unable to read storage', 'en'],
  '检查更新': ['Check for Updates', 'en'],
  '支持离线使用；发现新版本时顶部会提示一键更新。': ['Works offline; a banner will appear when a new version is found.', 'en'],
  '✨ 发现新版本，点击重启应用': ['✨ New version available, tap to restart', 'en'],
  '请输入密码': ['Enter password', 'en'],
  '解锁': ['Unlock', 'en'],
  '密码错误': ['Wrong password', 'en'],
  '已解锁 🔓': ['Unlocked 🔓', 'en'],
  '为 ': ['Add record for ', 'en'],
  ' 添加记录': ['', 'en'],
  '编辑记录': ['Edit Record', 'en'],
  '心情（可选）': ['Mood (optional)', 'en'],
  '备注（可选）': ['Note (optional)', 'en'],
  '照片（最多 9 张，可选）': ['Photos (max 9, optional)', 'en'],
  '＋ 添加照片': ['+ Add Photos', 'en'],
  '照片会压缩后保存在本机浏览器中。': ['Photos are compressed and stored locally.', 'en'],
  '完成状态': ['Status', 'en'],
  '数值': ['Value', 'en'],
  '收缩压（高压）': ['Systolic (high)', 'en'],
  '舒张压（低压）': ['Diastolic (low)', 'en'],
  '每天一条记录：三组可分批填写，之后随时编辑补齐。': ['One record per day: fill the three slots anytime and edit later.', 'en'],
  '至少填写一组数值': ['Fill at least one value', 'en'],
  '请填写收缩压和舒张压': ['Please fill systolic and diastolic', 'en'],
  '保存专注时间': ['Save Focus Time', 'en'],
  '要保存到今天的记录吗？': ['Save to today\'s record?', 'en'],
  '放弃': ['Discard', 'en'],
  '已保存 ': ['Saved ', 'en'],
  ' 分钟': [' min', 'en'],
  '已更新': ['Updated', 'en'],
  '已记录 🎉': ['Recorded 🎉', 'en'],
  '已补录': ['Added to today\'s record', 'en'],
  '开始专注 🎯': ['Focus started 🎯', 'en'],
  '已暂停': ['Paused', 'en'],
  '继续计时': ['Resumed', 'en'],
  '已放弃本次计时': ['Discarded this session', 'en'],
  '正在升级，马上回来…': ['Upgrading, back in a moment…', 'en'],
  '已是最新版本': ['Already up to date', 'en'],
  '正在检查更新…': ['Checking for updates…', 'en'],
  '发现新版本，点顶部横幅升级': ['New version found, tap the banner', 'en'],
  '当前环境不支持在线更新': ['Online updates not supported here', 'en'],
  '音乐已开启 🎵': ['Music on 🎵', 'en'],
  '🎵 点一下屏幕即可开启背景音乐': ['🎵 Tap the screen to start background music', 'en'],
  '已切换到「': ['Switched to "', 'en'],
  '」风格': ['" style', 'en'],
  '请输入名称': ['Please enter a name', 'en'],
  '密码至少 4 位': ['Password must be at least 4 characters', 'en'],
  '两次输入的密码不一致': ['Passwords do not match', 'en'],
  '应用锁已开启 🔒': ['App lock enabled 🔒', 'en'],
  '请输入当前密码': ['Enter the current password', 'en'],
  '应用锁已关闭': ['App lock disabled', 'en'],
  '已恢复默认图标': ['Icon reset to default', 'en'],
  '图标文件已导出': ['Icon file exported', 'en'],
  '请先上传一张图标': ['Please upload an icon first', 'en'],
  '迁移助手': ['Migration Assistant', 'en'],
  '换新地址/新版本后，按下面两步把旧数据搬过来：': ['Moving to a new address/version? Follow these two steps:', 'en'],
  '在旧版 App 打开「设置 → 数据备份 → 导出 JSON」': ['In the OLD app: Settings → Data Backup → Export JSON', 'en'],
  '回到本页点「导入 JSON」，选择刚才导出的文件': ['Back here, tap Import JSON and pick that file', 'en'],
  '分钟': ['min', 'en'],
  '未知项目': ['Unknown Project', 'en'],
  '未填写': ['Not filled', 'en'],
  '次': ['times', 'en'],
  '个': ['items', 'en'],
  '本次专注了': ['You focused', 'en'],
  '数据保存在当前浏览器的本地存储中，建议定期导出备份；换设备或换浏览器时再导入即可恢复。': ['Data is stored locally in this browser. Export backups regularly; import to restore on another device or browser.', 'en'],
  '每次更新加了什么、修了什么，都记在这里。': ['What is new and what was fixed — all recorded here.', 'en'],
  '选择喜欢的纯音乐风格；顶部 🎵 按钮可随时静音。': ['Choose a music style; the 🎵 button can mute it anytime.', 'en'],
  '设置后，打开应用需要输入密码才能查看，防止别人看到你的记录和照片（密码只保存在本机，不会上传）。': ['Lock the app with a password to protect your records and photos (stored only on this device).', 'en'],
  '新密码': ['New Password', 'en'],
  '再次输入': ['Confirm Password', 'en'],
  '当前密码（关闭时需要）': ['Current password (needed to disable)', 'en'],
  '照片存储在大容量本地数据库，不再占用网页存储空间。': ['Photos are stored in a large local database.', 'en'],
  '点横幅可展开/收起；在「今日」页点项目卡片即可开始记录。': ['Tap a banner to expand/collapse; tap a project card on Today to start recording.', 'en'],
  '检查更新失败，请稍后再试': ['Update check failed, try again later', 'en'],
  '离线版本尚未安装': ['Offline version not installed yet', 'en'],
  '请选择图片文件': ['Please choose an image file', 'en'],
  '图片处理失败，请换一张试试': ['Image processing failed, try another one', 'en'],
  '图片读取失败': ['Failed to read the image', 'en'],
  '应用图标已更新 🎉': ['App icon updated 🎉', 'en'],
  '已恢复默认图标': ['Icon reset to default', 'en'],
  '请先上传一张图标': ['Please upload an icon first', 'en'],
  '图标文件已导出': ['Icon file exported', 'en'],
  '图标导出失败': ['Icon export failed', 'en'],
  '照片读取失败': ['Failed to read photo', 'en'],
  '请先选择爱好': ['Please choose a project first', 'en'],
  '请先选择项目': ['Please choose a project first', 'en'],
  '确定删除这条记录吗？': ['Delete this record?', 'en'],
  '确定删除「': ['Delete "', 'en'],
  '」吗？': ['"?', 'en'],
  '将同时删除它的 ': ['It will also delete its ', 'en'],
  ' 条记录。': [' record(s).', 'en'],
  '已删除': ['Deleted', 'en'],
  '确定清空全部数据吗？此操作无法撤销。': ['Clear ALL data? This cannot be undone.', 'en'],
  '再次确认：所有项目和记录都会被删除。': ['Confirm again: all projects and records will be deleted.', 'en'],
  '已清空': ['Cleared', 'en'],
  '导入成功 ✅': ['Imported ✅', 'en'],
  '导入失败：文件格式不正确': ['Import failed: invalid file format', 'en'],
  '已导出备份文件': ['Backup exported', 'en'],
  '已是最新版本': ['Already up to date', 'en'],
  '正在升级，马上回来…': ['Upgrading, back in a moment…', 'en'],
  '请选择爱好': ['Please choose a project', 'en'],
  '已取消本次打卡': ['Removed from today', 'en'],
  '已记录 🎉': ['Recorded 🎉', 'en'],
  '这个分类还没有数据，去今日页开始记录吧。': ['No data for this category yet. Start recording on Today.', 'en'],
  '收缩压': ['Systolic', 'en'],
  '舒张压': ['Diastolic', 'en'],
  '连续': ['Streak', 'en'],
  '还没有项目': ['No projects yet', 'en'],
  '我的项目': ['My Projects', 'en']
};

function currentLang() {
  return localStorage.getItem(LANG_KEY) === 'en' ? 'en' : 'zh';
}
function setLang(lang) {
  localStorage.setItem(LANG_KEY, lang === 'en' ? 'en' : 'zh');
  document.documentElement.lang = currentLang() === 'en' ? 'en' : 'zh-CN';
}
function T(s) {
  if (currentLang() === 'zh') return s;
  const entry = LANG_DICT[s];
  return entry ? entry[0] : s;
}
function fmtDateLocal(s) {
  const d = parseDate(s);
  if (currentLang() === 'en') {
    return `${d.getMonth() + 1}/${d.getDate()}`;
  }
  return `${d.getMonth() + 1}月${d.getDate()}日`;
}
function weekLabelLocal(s) {
  const names = currentLang() === 'en' ? ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] : ['日', '一', '二', '三', '四', '五', '六'];
  return currentLang() === 'en' ? names[parseDate(s).getDay()] : '周' + names[parseDate(s).getDay()];
}
function fmtFullDateLocal(s) {
  const d = parseDate(s);
  if (currentLang() === 'en') {
    return `${d.getFullYear()}/${d.getMonth() + 1}/${d.getDate()}`;
  }
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日`;
}
